### PR TITLE
Redesign login screen

### PR DESCRIPTION
**Pull request by SpaceMercury**
This PR simply adds the logo for our application. Login screen now looks decent.

image_2024-04-09_151157598

### CODE REVIEW

**Review by JCHAVEROT — CHANGES_REQUESTED** [review]
The app logo looks so good, incredible !! 
Just don't forget the KTFmt for the CI, otherwise LGTM

**Review by theoschiff — CHANGES_REQUESTED** [review]
Hi Pol, Logo looks great ! However could you please add the TestTag(s) in the `Login` function so that the LoginTest passes ? These are the three you should add 

1. "LoginScreen" in the Column modifier 
2. "LoginTitle" in the Text title modifier
3. "LoginButton" in the Button modifier 

Also, I don't know if it's me but I think that the background colour is not exactly white and the logo's background is white, thus we can see the outline and doesn't look as good. If maybe you could fix this, it would look even better in my opinion

**Review by JCHAVEROT — APPROVED** [review]
All good now !

**Review by theoschiff — APPROVED** [review]
Looks good now, Thanks!

**Pull request merged**
